Assignment 4  (#31)
* Tar Command check

* Reorganizing the repo

* Checking upload and download archive

* Removing artifacts

* Setting up packer

* Provisioner file solve

* Building Image using packer

* Checking the whole workflow

* added a need command

* Packer CI/CD Complete

* Pakcer CI/CD Complete

* Build image with packer on pull request merge

* Checking new credentials

* Reverting to original workflow

* Fixing image name on packer

* Changed trigger

* Assignment 4 (Packer merge CI/CD) (#23)

* Tar Command check

* Reorganizing the repo

* Checking upload and download archive

* Removing artifacts

* Setting up packer

* Provisioner file solve

* Building Image using packer

* Checking the whole workflow

* added a need command

* Packer CI/CD Complete

* Pakcer CI/CD Complete

* Build image with packer on pull request merge

* Reorganizing the repo

* Provisioner file solve

* Packer CI/CD Complete

* Correct Instance Name and source

* Build Check:

* Run packer on pull request open

* Checking secret

* Added id:auth

* Remving id

* Trying to run after merge

* Checking on fork

* Checking with new secrets

* Trying new secret on org

* Checking if secret file is loaded or not

* Changing ls command

diff --git a/.github/workflows/building_image_using_packer.yml b/.github/workflows/building_image_using_packer.yml
--- a/.github/workflows/building_image_using_packer.yml
+++ b/.github/workflows/building_image_using_packer.yml
@@ -1,14 +1,18 @@
 name: "Build Image using Packer"
-on:
-  pull_request:
-    types:
-      - closed
-    branches:
-      - main
 # on:
 #   pull_request:
 #     types:
-#       - opened
+#       - closed
+#     branches:
+#       - main
+on:
+  pull_request:
+    types:
+      - opened
+# on:
+#   push:
+#     branches: 
+#       - assignment_4
 jobs:
   # test:
   #   runs-on: ubuntu-latest
@@ -44,9 +48,9 @@ jobs:
       - name: Get Code
         uses: actions/checkout@v3
       - name: Use secret
-        run: echo "Secret value is ${{ secrets.GCP_CREDENTIALS }}"
-        env:
-          MY_SECRET_VALUE: ${{ secrets.GCP_CREDENTIALS }}
+        run: |
+         echo "Secret value is ${{ secrets.GCP_CREDENTIALS }}"
+         ls -la
       - name: Authenticate Google Cloud
         uses: google-github-actions/auth@v2
         with:
@@ -59,17 +63,17 @@ jobs:
         continue-on-error: true
         run: |
           gcloud compute images delete "centos-image" --quiet
-      - name: Create a zip
-        run: |
-          tar -czvf webapp.tar.gz . || echo "tar command failed"
-          ls -la
-      - name: Setup Packer
-        uses: hashicorp/setup-packer@main
-      - name: Pre Steps of packer
-        run: |
-          packer init ./packer/main.pkr.hcl
-          packer fmt ./packer/main.pkr.hcl
-          packer validate ./packer/main.pkr.hcl
-      - name: Build Packer
-        run: packer build ./packer/main.pkr.hcl
+      # - name: Create a zip
+      #   run: |
+      #     tar -czvf webapp.tar.gz . || echo "tar command failed"
+      #     ls -la
+      # - name: Setup Packer
+      #   uses: hashicorp/setup-packer@main
+      # - name: Pre Steps of packer
+      #   run: |
+      #     packer init ./packer/main.pkr.hcl
+      #     packer fmt ./packer/main.pkr.hcl
+      #     packer validate ./packer/main.pkr.hcl
+      # - name: Build Packer
+      #   run: packer build ./packer/main.pkr.hcl
 # if: ${{ github.event.pull_request.merged == true }}
